### ISSUE TITLE
BUG - Update fivetran/fivetran_utils dependency to newer version for compatibility

### ISSUE THREAD

**Issue by rodrigo4244** [fivetran/dbt_xero_source#9]
**Are you a current Fivetran customer?** 
Name: Rodrigo Gonçalves de Oliveira
Title: Software Engineer
Company: Invisible Technologies

**Describe the bug**
We are trying to use in parallel `fivetran/jira`, `fivetran/ad_reporting` and `fivetran/xero` packages for DBT and are encountering package resolution issues due to incompatible versions of `fivetran/fivetran_utils` package. 

**Steps to reproduce**
New DBT project with `fivetran/jira`, `fivetran/ad_reporting` and `fivetran/xero` dependencies and run `dbt deps` on it.

**Expected behavior**
To install the packages and do the transformations for us.

**Package Version**
![image](https://user-images.githubusercontent.com/8367325/130262435-7b5767ef-2cca-4213-9a79-30415fb0d73d.png)

**Warehouse**
- [ ] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [X] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Screenshots**
Same as the one for package version

**Please indicate the level of urgency** 
Trying to use `fivetran/jira` for the first time

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [X] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
@rodrigo4244 thanks so much for raising this issue! Our team has recently upgraded our dbt packages to be compatibile with dbt 0.20.0. However, it seems Xero was not updated during this process. I will update and cut a release to fix this today.

I will post back here once we are able to cut the newest release.

**Comment by fivetran-joemarkiewicz** [comment]
@rodrigo4244 the Xero `v0.2.0` version is now live on the dbt hub! This will be able to be installed in tandem with the Jira and ad_reporting package versions you have specified. Thanks again for raising this issue!
